version: '3.8'

services:
  workshop:
    image: thesmallhancat/workshop:latest
    container_name: workshop
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./config/setting.toml:/app/config/setting.toml
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
